In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import kwat

## apply

In [3]:
ar = np.array([np.nan, 0, 1, 2, np.nan])

In [4]:
np.sum(ar)

nan

In [5]:
kwat.array.apply(ar, np.sum)

3.0

In [6]:
np.cumsum(ar)

array([nan, nan, nan, nan, nan])

In [7]:
kwat.array.apply(ar, np.cumsum)

array([0., 1., 3.])

In [8]:
kwat.array.apply(ar, np.cumsum, up=True)

array([nan,  0.,  1.,  3., nan])

## check_is_extreme

In [9]:
ar = np.arange(10)

for di in ["<", ">", "<>"]:

    print()

    print(di)

    for ke_ in [
        {
            "th_": (2, np.nan),
        },
        {
            "th_": (np.nan, 8),
        },
        {
            "n_ex": 2,
        },
        {
            "st": 2,
        },
    ]:

        print(ke_)

        print(ar[kwat.array.check_is_extreme(ar, di, **ke_)])


<
{'th_': (2, nan)}
[0 1 2]
{'th_': (nan, 8)}
[]
{'n_ex': 2}
[0 1]
{'st': 2}
[]

>
{'th_': (2, nan)}
[]
{'th_': (nan, 8)}
[8 9]
{'n_ex': 2}
[8 9]
{'st': 2}
[]

<>
{'th_': (2, nan)}
[0 1 2]
{'th_': (nan, 8)}
[8 9]
{'n_ex': 2}
[0 1 8 9]
{'st': 2}
[]


## check_is_not_nan

In [10]:
kwat.array.check_is_not_nan([np.nan, 0, 1.0, 2, False, True, np.nan])

array([False,  True,  True,  True,  True,  True, False])

## clip

In [11]:
ar = np.arange(-2, 3)

for st in [0, 1, 2]:

    print(kwat.array.clip(ar, st))

[0. 0. 0. 0. 0.]
[-1.41421356 -1.          0.          1.          1.41421356]
[-2. -1.  0.  1.  2.]


## get_not_nan_unique

In [12]:
kwat.array.get_not_nan_unique(np.array([np.nan, 0, 1.0, 2, 2, False, True, np.nan]))

array([0., 1., 2.])

## guess_type

In [13]:
for ar in [
    [0],
    [1],
    [0, 1],
    [0, 1, 2],
    np.arange(16),
    [0.0],
    [0.1],
    [1.0],
    [0, 0.0],
    [0, 0.0, 1, 1.0],
    np.arange(17),
    np.random.random_sample(4),
]:

    print(kwat.array.guess_type(np.array(ar)))

binary
binary
binary
categorical
categorical
binary
continuous
binary
binary
binary
continuous
continuous


## log

In [14]:
ar = np.array([1, 2, np.inf])

for ba in [2, "e", 10]:

    print(kwat.array.log(ar, ba=ba))

[ 0.  1. inf]
[0.         0.69314718        inf]
[0.      0.30103     inf]


## log_with_negative

In [15]:
kwat.array.log_with_negative(np.array([-2, -1, 0, 1, 2]))

array([-1.5849625, -1.       ,  0.       ,  1.       ,  1.5849625])

## normalize

In [16]:
for ar in [[0, 1], [[0, 1, 2], [0, 10, 20]]]:

    ar = np.array(ar)

    print()

    print(ar)

    for me in ["-0-", "0-1", "sum", "rank"]:

        print(me)

        print(kwat.array.normalize(ar, me))


[0 1]
-0-
[-1.  1.]
0-1
[0. 1.]
sum
[0. 1.]
rank
[1. 2.]

[[ 0  1  2]
 [ 0 10 20]]
-0-
[[-0.74903338 -0.61284549 -0.47665761]
 [-0.74903338  0.61284549  1.97472437]]
0-1
[[0.   0.05 0.1 ]
 [0.   0.5  1.  ]]
sum
[[0.         0.03030303 0.06060606]
 [0.         0.3030303  0.60606061]]
rank
[[1.5 3.  4. ]
 [1.5 5.  6. ]]


## shift

In [17]:
ar = np.array([-1, 0, 0.5, 2])

for mi in [-1, 0, 1, "0<"]:

    print(mi)

    print(kwat.array.shift(ar, mi))

-1
[-1.   0.   0.5  2. ]
0
[0.  1.  1.5 3. ]
1
[1.  2.  2.5 4. ]
0<
Shifting the minimum to 0.5...
[0.5 1.5 2.  3.5]
