In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

## error_nan

In [3]:
kraft.error_nan(np.asarray((0, 1)))

In [4]:
try:

    kraft.error_nan(np.asarray((2, np.nan)))

except AssertionError as error:

    print(error)

## is_sortred

In [5]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 1),
    (1, 0),
    (0, 1, 0),
    (1, 0, 1),
):

    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.is_sorted(numbers))

[0]
True
[0. 0.]
True
[0 1]
True
[1 0]
True
[0 1 0]
False
[1 0 1]
False


## guess_type

In [6]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 1),
    (0, 1, 0.0, 1.0),
    np.random.randint(2, size=(2, 4)),
    (0, 1, 2),
    tuple(range(16)),
    np.random.randint(3, size=(2, 4)),
    (0.1,),
    tuple(range(17)),
    np.random.random_sample(size=(2, 4)),
):

    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.guess_type(numbers))

[0]
binary
[0. 0.]
binary
[0 1]
binary
[0. 1. 0. 1.]
binary
[[0 0 0 1]
 [1 0 0 0]]
binary
[0 1 2]
categorical
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
categorical
[[1 1 1 0]
 [0 1 1 2]]
categorical
[0.1]
continuous
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
continuous
[[0.16800843 0.04041393 0.83620095 0.17326555]
 [0.16746525 0.11501256 0.77705495 0.68631047]]
continuous


## clip

In [7]:
array = np.arange(-2, 3)

print(array)

[-2 -1  0  1  2]


In [8]:
for standard_deviation in range(3):

    print(standard_deviation)

    array_ = kraft.clip(array, standard_deviation)

    assert array is not array_

    print(array_)

0
[0. 0. 0. 0. 0.]
1
[-1.41421356 -1.          0.          1.          1.41421356]
2
[-2. -1.  0.  1.  2.]


## shift_minimum

In [9]:
array = np.asarray((-1, 0, 0.5, 2))

print(array)

[-1.   0.   0.5  2. ]


In [10]:
for minimum in (-1, 0, 1, "0<"):

    print(minimum)

    array_ = kraft.shift_minimum(array, minimum)

    assert array is not array_

    print(array_)

-1
[-1.   0.   0.5  2. ]
0
[0.  1.  1.5 3. ]
1
[1.  2.  2.5 4. ]
0<
[0.5 1.5 2.  3.5]


## log

In [11]:
array = np.asarray((1, 2, np.inf))

print(array)

[ 1.  2. inf]


In [12]:
for log_base in (
    2,
    "2",
    "e",
    10,
    "10",
):

    print(log_base)

    print(kraft.log(array, log_base=log_base,))

2
[ 0.  1. inf]
2
[ 0.  1. inf]
e
[0.         0.69314718        inf]
10
[0.      0.30103     inf]
10
[0.      0.30103     inf]


## normalize

In [13]:
for array in (
    np.asarray((0, 1)),
    np.asarray(((0, 1, 2), (0, 10, 20))),
):

    print(array)

    for method in ("-0-", "0-1", "sum", "rank"):

        print(method)

        print(kraft.normalize(array, method))

[0 1]
-0-
[-1.  1.]
0-1
[0. 1.]
sum
[0. 1.]
rank
[1. 2.]
[[ 0  1  2]
 [ 0 10 20]]
-0-
[[-0.74903338 -0.61284549 -0.47665761]
 [-0.74903338  0.61284549  1.97472437]]
0-1
[[0.   0.05 0.1 ]
 [0.   0.5  1.  ]]
sum
[[0.         0.03030303 0.06060606]
 [0.         0.3030303  0.60606061]]
rank
[1.5 3.  4.  1.5 5.  6. ]


## ignore_nan_and_function_1

In [14]:
array = np.asarray((np.nan, 0, 1, 2, np.nan))

print(array)

[nan  0.  1.  2. nan]


In [15]:
print(np.sum(array))

print(kraft.ignore_nan_and_function_1(array, np.sum))

nan
3.0


In [16]:
print(np.cumsum(array))

array_ = kraft.ignore_nan_and_function_1(array, np.cumsum, update=True)

assert array_ is not array

print(array_)

[nan nan nan nan nan]
[nan  0.  1.  3. nan]


## ignore_nan_and_function_2

In [17]:
array_0 = np.asarray((np.nan, 0, 1, np.nan, 2))

print(array_0)

array_1 = np.asarray((np.nan, 0, 1, 2, np.nan))

print(array_1)

print(np.add(array_0, array_1))

print(kraft.ignore_nan_and_function_2(array_0, array_1, np.add))

[nan  0.  1. nan  2.]
[nan  0.  1.  2. nan]
[nan  0.  2. nan nan]
[0. 2.]
