In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

## clip

In [3]:
array = np.arange(-2, 3)

array

array([-2, -1,  0,  1,  2])

In [4]:
for standard_deviation in range(3):

    print(standard_deviation)

    output = kraft.clip(array, standard_deviation)

    assert array is not output

    print(output)

0
[0. 0. 0. 0. 0.]
1
[-1.41421356 -1.          0.          1.          1.41421356]
2
[-2. -1.  0.  1.  2.]


## error_nan

In [5]:
kraft.error_nan(np.asarray((0, 1)))

try:

    kraft.error_nan(np.asarray((2, np.nan)))

except AssertionError as error:

    print(error)

## guess_type

In [7]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 1),
    (0, 1, 0.0, 1.0),
    np.random.randint(2, size=(2, 4)),
    (0, 1, 2),
    tuple(range(16)),
    np.random.randint(3, size=(2, 4)),
    (0.1,),
    tuple(range(17)),
    np.random.random_sample(size=(2, 4)),
):

    print()
    
    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.guess_type(numbers))


[0]
binary

[0. 0.]
binary

[0 1]
binary

[0. 1. 0. 1.]
binary

[[1 0 1 1]
 [1 0 0 0]]
binary

[0 1 2]
categorical

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
categorical

[[2 2 0 1]
 [2 1 1 2]]
categorical

[0.1]
continuous

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
continuous

[[0.14209042 0.5686764  0.59637111 0.63266475]
 [0.01190839 0.93853713 0.0923465  0.18420956]]
continuous


## ignore_nan_and_function_1

In [8]:
array = np.asarray((np.nan, 0, 1, 2, np.nan))

array

array([nan,  0.,  1.,  2., nan])

In [9]:
print(np.sum(array))

output = kraft.ignore_nan_and_function_1(array, np.sum)

assert output is not array

print(output)

nan
3.0


In [10]:
print(np.cumsum(array))

output = kraft.ignore_nan_and_function_1(array, np.cumsum, update=True)

assert output is not array

print(output)

[nan nan nan nan nan]
[nan  0.  1.  3. nan]


## ignore_nan_and_function_2

In [11]:
array_0 = np.asarray((np.nan, 0, 1, np.nan, 2))

print(array_0)

array_1 = np.asarray((np.nan, 0, 1, 2, np.nan))

print(array_1)

print(np.add(array_0, array_1))

print(kraft.ignore_nan_and_function_2(array_0, array_1, np.add))

[nan  0.  1. nan  2.]
[nan  0.  1.  2. nan]
[nan  0.  2. nan nan]
[0. 2.]


## is_sortred

In [13]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 1),
    (1, 0),
    (0, 1, 0),
    (1, 0, 1),
):

    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.is_sorted(numbers))

[0]
True
[0. 0.]
True
[0 1]
True
[1 0]
True
[0 1 0]
False
[1 0 1]
False


## log

In [14]:
array =  np.asarray((1, 2, np.inf))

array

array([ 1.,  2., inf])

In [15]:
for log_base in (
    2,
    "2",
    "e",
    10,
    "10",
):

    print(log_base)

    print(
        kraft.log(
            array,  log_base=log_base,
        )
    )

2
[ 0.  1. inf]
2
[ 0.  1. inf]
e
[0.         0.69314718        inf]
10
[0.      0.30103     inf]
10
[0.      0.30103     inf]


## normalize

In [16]:
for array in (
    np.asarray((0, 1)),
    np.asarray((0, 0)),
    np.asarray((0,)),
):

    print()

    print(array)

    for method in ("-0-", "0-1", "sum", "rank"):

        print(method)

        print(kraft.normalize(
            array, method
        ))


[0 1]
-0-
[-1.  1.]
0-1
[0. 1.]
sum
[0. 1.]
rank
[1. 2.]

[0 0]
-0-


AssertionError: 

In [ ]:
for _2d_array in (
    np.asarray(((0, 1, 2), (3, 4, 5), (6, 7, 8)), dtype=float),
    np.asarray(((np.nan, 0, 1, 2), (3, np.inf, 4, 5), (6, 7, -np.inf, 8))),
):

    print()
    
    print(_2d_array)

    for axis in (None, 0, 1):

        for method in ("-0-", "0-1", "sum", "rank"):

            print()

            print(axis, method)

            normalized_2d_array = ccal.normalize_nd_array(
                _2d_array, axis, method, raise_for_bad=False
            )

            print(normalized_2d_array)

## shift_minimum

In [ ]:
array =  np.asarray((-1, 0, 0.5, 2))

array

In [ ]:
for minimum in (-1, 0, 1, "0<"):

    print(minimum)

    output = kraft.shift_minimum(array, minimum)

    print(output)