In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [5]:
array = np.arange(-2, 4)

array

array([-2, -1,  0,  1,  2,  3])

In [6]:
for standard_deviation in (-1, 0, 1, 1.1):

    print(kraft.clip_by_standard_deviation(array, standard_deviation))

[-1.20782513 -1.20782513 -1.20782513 -1.20782513 -1.20782513 -1.20782513]
[0.5 0.5 0.5 0.5 0.5 0.5]
[-1.20782513 -1.          0.          1.          2.          2.20782513]
[-1.37860764 -1.          0.          1.          2.          2.37860764]
