In [1]:
import numpy as np

In [2]:
point_x_dimension = np.asarray(
    (
        (-8, -8, -8),
        (-1, -1, -1),
        (0, 0, 0),
        (1, 1, 1),
        (8, 8, 8),
        (10, 10, 10),
        (16, 16, 16),
        (88, 88, 88),
    )
)

point_x_dimension

array([[-8, -8, -8],
       [-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1],
       [ 8,  8,  8],
       [10, 10, 10],
       [16, 16, 16],
       [88, 88, 88]])

In [3]:
import ccal

CCAL version 1.1.0 @ /home/kwatme/github/ccal/ccal/__init__.py


In [4]:
for n_target_dimension in (1, 2, 3):

    point_x_target_dimension = ccal.reduce_point_x_dimension_dimension(
        n_target_dimension, point_x_dimension=point_x_dimension
    )

    print(point_x_target_dimension)

[[-38.53813047]
 [-26.41377482]
 [-24.68172401]
 [-22.9496732 ]
 [-10.82531755]
 [ -7.36121593]
 [  3.03108891]
 [127.73874706]]
[[-37.16138481  10.07914878]
 [-24.89586118   8.64380848]
 [-23.72719213   6.91473932]
 [-21.93965209   6.75562243]
 [-10.60652988   2.09955483]
 [ -6.7105509    3.48445453]
 [  2.36787808  -2.3761323 ]
 [122.67329289 -35.60119607]]
[[ 29.3743597  -13.61542726  20.71392418]
 [ 19.86793334  -8.13315874  15.26902353]
 [ 18.08441826  -7.5667965   14.97990683]
 [ 17.21633654  -6.71179579  13.55363956]
 [  6.99995428  -5.57658701   6.51149495]
 [  4.38251287  -4.11732545   4.62896541]
 [ -0.75517955   3.72556136  -1.54138023]
 [-95.17033543  41.99552939 -74.11557423]]


In [5]:
from scipy.spatial.distance import euclidean, pdist, squareform

point_x_target_dimension = ccal.reduce_point_x_dimension_dimension(
    2, distance__point_x_point=squareform(pdist(point_x_dimension))
)

point_x_target_dimension

array([[-37.16138481,  10.07914878],
       [-24.89586118,   8.64380848],
       [-23.72719213,   6.91473932],
       [-21.93965209,   6.75562243],
       [-10.60652988,   2.09955483],
       [ -6.7105509 ,   3.48445453],
       [  2.36787808,  -2.3761323 ],
       [122.67329289, -35.60119607]])

In [6]:
from scipy.spatial.distance import chebyshev

point_x_target_dimension = ccal.reduce_point_x_dimension_dimension(
    2, point_x_dimension=point_x_dimension, distance_function=chebyshev
)

point_x_target_dimension

array([[-21.45484876,   5.81628845],
       [-14.36193515,   5.01216155],
       [-13.70565991,   3.97343166],
       [-12.6670303 ,   3.9016519 ],
       [ -6.13143518,   1.17667778],
       [ -3.86704416,   2.05324826],
       [  1.36262962,  -1.37920858],
       [ 70.82532385, -20.55425102]])