In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
for function in (np.random.random_sample, np.random.normal):

    print(function.__name__)

    for power in range(4):

        array = function(size=10 ** power)

        print(kraft.get_moe(array))

random_sample
0.0
0.13738995364434142
0.04974165572380757
0.014684895735066405
normal
0.0
0.3831260269364577
0.16690262595641614
0.05034389973194261


In [4]:
random_values = np.arange(10)

values = np.asarray((0, 1, 8, 9))

In [5]:
for value in values:

    print(value)

    for direction in ("<", ">"):

        print(direction)

        print(kraft.get_p_value(value, random_values, direction))

0
<
0.1
>
1.0
1
<
0.2
>
0.9
8
<
0.9
>
0.2
9
<
1.0
>
0.1


In [6]:
for direction in ("<", ">", "<>"):

    print(kraft.get_p_values_and_q_values(values, random_values, direction))

(array([0.1, 0.2, 0.9, 1. ]), array([0.4, 0.4, 1. , 1. ]))
(array([1. , 0.9, 0.2, 0.1]), array([1. , 1. , 0.4, 0.4]))
(array([0.1, 0.2, 0.2, 0.1]), array([0.4, 0.4, 0.4, 0.4]))
