In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
for vector_0, vector_1 in (
    (np.asarray((0,) * 8),) * 2,
    (np.asarray((1,) * 8),) * 2,
    (np.arange(8), np.arange(8)[::-1]),
    (np.asarray((0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1, 0)),) * 2,
    (np.asarray((8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8)),) * 2,
    (np.asarray((0, 1) * 8), np.asarray((0, 1) * 8)),
    (np.asarray((0, 1) * 8), np.asarray((1, 0) * 8)),
):

    print(vector_0)

    print(vector_1)

    print(kraft.get_ic(vector_0, vector_1))

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
nan
[1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1]
nan
[0 1 2 3 4 5 6 7]
[7 6 5 4 3 2 1 0]
-0.9358607364141003
[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
0.9509464952026275
[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
0.9509464952026275
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
0.8660254037844094
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
-0.8660254037844094


In [4]:
for power in range(9):

    n = 2 ** power

    print(n)

    vector_0 = np.random.normal(size=n)

    vector_1 = np.random.normal(size=n)

    print(kraft.get_ic(vector_0, vector_1))

1
nan
2
0.8648371747066395
4
0.6787973273928825
8
0.37967135595456636
16
0.3901979901173882
32
-0.3648491033958157
64
-0.35568212185116727
128
0.32642383665311503
256
0.2667980855087445


In [5]:
n = 2

vector_0 = np.asarray((0,) * n + (1,) * n + (2,) * n)

for factor in (1, 2, 1 / 2, 10, 1 / 10):

    vector_1 = vector_0 * factor

    print(vector_1)

    print(kraft.get_ic(vector_0, vector_1))

[0 0 1 1 2 2]
0.9346545226262682
[0 0 2 2 4 4]
0.9346545226262682
[0.  0.  0.5 0.5 1.  1. ]
0.9346545226262682
[ 0  0 10 10 20 20]
0.9346545226262682
[0.  0.  0.1 0.1 0.2 0.2]
0.9346545226262682


In [6]:
n = 100

for function in (np.random.random_sample, np.random.normal):

    print(function.__name__)

    vector_0 = function(size=n)

    vector_1 = function(size=n)

    print(kraft.get_ic(vector_0, vector_1))

random_sample
-0.16181280749021645
normal
-0.3297065246933263


In [7]:
%%timeit

kraft.get_ic(vector_0, vector_1)

3.64 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
