In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd

import kraft

In [3]:
array = np.asarray((np.nan, 0, 1, 2))

array

array([nan,  0.,  1.,  2.])

In [4]:
print(np.sum(array))

kraft.ignore_nan_and_function_1(array, np.sum)

nan


3.0

In [5]:
print(kraft.normalize(array, "rank"))

kraft.ignore_nan_and_function_1(array, kraft.normalize, "rank", update=True)

[4. 1. 2. 3.]


array([nan,  1.,  2.,  3.])

In [6]:
array_0 = np.asarray((np.nan, 0, 1, np.nan, 2))

array_1 = np.asarray((np.nan, 0, 1, 2, np.nan))

print(np.add(array_0, array_1))

kraft.ignore_nan_and_function_2(array_0, array_1, np.add)

[nan  0.  2. nan nan]


array([0., 2.])