In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import kraft

In [4]:
np.random.seed(seed=kraft.RANDOM_SEED)

In [5]:
for power in range(9):

    n = 2 ** power

    print(
        f"{kraft.compute_1d_array_entropy(np.random.random_sample(size=n))} ({n} random)"
    )

    for value in (1, 2, 8):

        print(f"{kraft.compute_1d_array_entropy(np.full(n, value))} ({n} {value})")

-0.0 (1 random)
-0.0 (1 1)
-0.0 (1 2)
-0.0 (1 8)
0.6462596793146722 (2 random)
0.6931471805599453 (2 1)
0.6931471805599453 (2 2)
0.6931471805599453 (2 8)
1.1187020415455604 (4 random)
1.3862943611198906 (4 1)
1.3862943611198906 (4 2)
1.3862943611198906 (4 8)
1.9469474216073919 (8 random)
2.0794415416798357 (8 1)
2.0794415416798357 (8 2)
2.0794415416798357 (8 8)
2.5351989204983 (16 random)
2.772588722239781 (16 1)
2.772588722239781 (16 2)
2.772588722239781 (16 8)
3.305259305271915 (32 random)
3.4657359027997265 (32 1)
3.4657359027997265 (32 2)
3.4657359027997265 (32 8)
4.005490084024379 (64 random)
4.1588830833596715 (64 1)
4.1588830833596715 (64 2)
4.1588830833596715 (64 8)
4.652365079229237 (128 random)
4.852030263919617 (128 1)
4.852030263919617 (128 2)
4.852030263919617 (128 8)
5.363952518752676 (256 random)
5.545177444479562 (256 1)
5.545177444479562 (256 2)
5.545177444479562 (256 8)


In [6]:
for _1d_array_0, _1d_array_1 in (
    (np.asarray((0,) * 8),) * 2,
    (np.asarray((1,) * 8),) * 2,
    (np.asarray(range(8)), np.asarray(range(8))[::-1]),
    (np.asarray((0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1, 0)),) * 2,
    (np.asarray((8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8)),) * 2,
    (np.asarray((0, 1) * 8), np.asarray((0, 1) * 8)),
    (np.asarray((0, 1) * 8), np.asarray((1, 0) * 8)),
):

    print(_1d_array_0)

    print(_1d_array_1)

    print(
        kraft.compute_information_coefficient_between_2_1d_arrays(
            _1d_array_0, _1d_array_1
        )
    )

    print(
        kraft.compute_information_distance_between_2_1d_arrays(_1d_array_0, _1d_array_1)
    )

    print()

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
nan
nan

[1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1]
nan
nan

[0 1 2 3 4 5 6 7]
[7 6 5 4 3 2 1 0]
-0.940909174550142
0.970454587275071

[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
0.9552971701194466
0.022351414940276704

[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
0.9552971701194466
0.022351414940276704

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
0.8660254037843793
0.06698729810781034

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
-0.8660254037843792
0.9330127018921897



In [7]:
for power in range(17):

    n = 2 ** power

    _1d_array_0 = np.random.normal(size=n)

    _1d_array_1 = np.random.normal(size=n)

    print(
        f"{kraft.compute_information_coefficient_between_2_1d_arrays(_1d_array_0, _1d_array_1)} (n={n})"
    )

nan (n=1)
0.865051755259572 (n=2)
-0.5462894604919197 (n=4)
-0.5519223168811476 (n=8)
0.3012532775077513 (n=16)
0.25059918290564104 (n=32)
0.2752449128837096 (n=64)
0.31671904092687964 (n=128)
0.23423704551838964 (n=256)
0.18491025066948183 (n=512)
0.21441454843461336 (n=1024)
-0.15835896281840467 (n=2048)
0.1305145288708445 (n=4096)
-0.1105694769817739 (n=8192)
-0.08765686209352265 (n=16384)
-0.07396288173170756 (n=32768)
0.0609569328391275 (n=65536)


In [8]:
n = 2

_1d_array_0 = np.asarray((0,) * n + (1,) * n + (2,) * n)

for factor in (1, 2, 1 / 2, 10, 1 / 10):

    _1d_array_1 = _1d_array_0 * factor

    print(_1d_array_0)

    print(_1d_array_1)

    print(
        kraft.compute_information_coefficient_between_2_1d_arrays(
            _1d_array_0, _1d_array_1
        )
    )

    print()

[0 0 1 1 2 2]
[0 0 1 1 2 2]
0.936579206750645

[0 0 1 1 2 2]
[0 0 2 2 4 4]
0.936579206750645

[0 0 1 1 2 2]
[0.  0.  0.5 0.5 1.  1. ]
0.936579206750645

[0 0 1 1 2 2]
[ 0  0 10 10 20 20]
0.936579206750645

[0 0 1 1 2 2]
[0.  0.  0.1 0.1 0.2 0.2]
0.936579206750645



In [9]:
n = 1000

_1d_array_0 = np.random.random_sample(size=n)

_1d_array_1 = np.random.random_sample(size=n)

In [10]:
%%timeit

kraft.compute_information_coefficient_between_2_1d_arrays_r(
    _1d_array_0,
    _1d_array_1,
)

17.5 ms ± 486 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
kraft.compute_information_coefficient_between_2_1d_arrays_r(_1d_array_0, _1d_array_1)

-0.11523099765801315

In [23]:
%%timeit

kraft.compute_information_coefficient_between_2_1d_arrays(
    _1d_array_0,
    _1d_array_1,
)

2.75 ms ± 65.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
kraft.compute_information_coefficient_between_2_1d_arrays(_1d_array_0, _1d_array_1)

-0.09575344762814487

In [14]:
import cProfile

In [15]:
cProfile.run(
    "kraft.compute_information_coefficient_between_2_1d_arrays(_1d_array_0, _1d_array_1)",
    sort="cumtime",
)

         2065 function calls in 0.006 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.006    0.006 {built-in method builtins.exec}
        1    0.000    0.000    0.005    0.005 <string>:1(<module>)
        1    0.000    0.000    0.005    0.005 compute_information_coefficient_between_2_1d_arrays.py:12(compute_information_coefficient_between_2_1d_arrays)
        1    0.000    0.000    0.004    0.004 FFTKDE.py:105(evaluate)
       12    0.000    0.000    0.002    0.000 kernel_funcs.py:289(evaluate)
        1    0.000    0.000    0.001    0.001 kernel_funcs.py:262(practical_support)
        1    0.000    0.000    0.001    0.001 zeros.py:629(brentq)
        1    0.000    0.000    0.001    0.001 {built-in method scipy.optimize._zeros._brentq}
       11    0.000    0.000    0.001    0.000 kernel_funcs.py:275(f)
       12    0.000    0.000    0.001    0.000 kernel_funcs.py:156(gaussian)
        1 