In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import kraft

In [4]:
np.random.seed(seed=kraft.RANDOM_SEED)

In [5]:
for power in range(9):
    
    n = 2**power
    
    print(f'{kraft.compute_1d_array_entropy(np.random.random_sample(size=n))} ({n} random)')
    
    for value in (1, 2, 8):

        print(f'{kraft.compute_1d_array_entropy(np.full(n, value))} ({n} {value})')

-0.0 (1 random)
-0.0 (1 1)
-0.0 (1 2)
-0.0 (1 8)
0.6462596793146722 (2 random)
0.6931471805599453 (2 1)
0.6931471805599453 (2 2)
0.6931471805599453 (2 8)
1.1187020415455604 (4 random)
1.3862943611198906 (4 1)
1.3862943611198906 (4 2)
1.3862943611198906 (4 8)
1.9469474216073919 (8 random)
2.0794415416798357 (8 1)
2.0794415416798357 (8 2)
2.0794415416798357 (8 8)
2.5351989204983 (16 random)
2.772588722239781 (16 1)
2.772588722239781 (16 2)
2.772588722239781 (16 8)
3.305259305271915 (32 random)
3.4657359027997265 (32 1)
3.4657359027997265 (32 2)
3.4657359027997265 (32 8)
4.005490084024379 (64 random)
4.1588830833596715 (64 1)
4.1588830833596715 (64 2)
4.1588830833596715 (64 8)
4.652365079229237 (128 random)
4.852030263919617 (128 1)
4.852030263919617 (128 2)
4.852030263919617 (128 8)
5.363952518752676 (256 random)
5.545177444479562 (256 1)
5.545177444479562 (256 2)
5.545177444479562 (256 8)


In [10]:
for _1d_array_0, _1d_array_1 in (
    (np.asarray((0,) * 8),) * 2,
    (np.asarray((1,) * 8),) * 2,
    (np.asarray(range(8)), np.asarray(range(8))[::-1]),
    (np.asarray((0, 1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1, 0)),) * 2,
    (np.asarray((8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8)),) * 2,
    (
        np.asarray((0, 1) * 8),
        np.asarray((0, 1) * 8),
    ),
    (
        np.asarray((0, 1) * 8),
        np.asarray((1, 0) * 8),
    ),
):

    print(_1d_array_0)

    print(_1d_array_1)
    
    print(kraft.compute_information_coefficient_between_2_1d_arrays(
            _1d_array_0,
            _1d_array_1,
        ))
    
    print(kraft.compute_information_distance_between_2_1d_arrays(
            _1d_array_0,
            _1d_array_1,
        ))
    
    print()

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
nan
nan

[1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1]
nan
nan

[0 1 2 3 4 5 6 7]
[7 6 5 4 3 2 1 0]
-0.6721132117505169
0.8360566058752584

[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0]
0.7311612530442776
0.1344193734778612

[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0 1 2 3 4 5 6 7 8]
0.7311612530442773
0.13441937347786137

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
0.7730192764982813
0.11349036175085936

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
-0.7730192764982815
0.8865096382491408



/home/kwat/miniconda3/lib/python3.6/site-packages/scipy/stats/stats.py:3038: RuntimeWarning:

invalid value encountered in double_scalars



In [11]:
for power in range(17):
    
    n = 2**power
    
    _1d_array_0 = np.random.normal(size=n)

    _1d_array_1 = np.random.normal(size=n)
    
    print(f'{kraft.compute_information_coefficient_between_2_1d_arrays(_1d_array_0, _1d_array_1)} (n={n})')

nan (n=1)
0.048450881732938225 (n=2)
-0.3979217611366719 (n=4)
-0.2360437154409888 (n=8)
0.2741467632107411 (n=16)
0.21626534476515238 (n=32)
0.23293932855255287 (n=64)
0.24536655608097133 (n=128)
0.2185710429001611 (n=256)
0.17150654762885686 (n=512)
0.20002763210553373 (n=1024)
-0.14148816481636892 (n=2048)
0.11725846147406889 (n=4096)
-0.09857564253654555 (n=8192)
-0.08034330581015345 (n=16384)
-0.06927643981048637 (n=32768)
0.05712052276104869 (n=65536)


/home/kwat/miniconda3/lib/python3.6/site-packages/scipy/stats/stats.py:3038: RuntimeWarning:

invalid value encountered in double_scalars



In [12]:
n = 2

_1d_array_0 = np.asarray((0,) * n + (1,) * n + (2,) * n)

for factor in (1, 2, 1/2, 10, 1/10):

    _1d_array_1 = _1d_array_0 * factor
    
    print(_1d_array_0)

    print(_1d_array_1)
    
    print(f'{kraft.compute_information_coefficient_between_2_1d_arrays(_1d_array_0, _1d_array_1)}')
    
    print()

[0 0 1 1 2 2]
[0 0 1 1 2 2]
0.6555793297646126

[0 0 1 1 2 2]
[0 0 2 2 4 4]
0.4584654504662818

[0 0 1 1 2 2]
[0.  0.  0.5 0.5 1.  1. ]
0.4576871348202127

[0 0 1 1 2 2]
[ 0  0 10 10 20 20]
0.11025793806583387

[0 0 1 1 2 2]
[0.  0.  0.1 0.1 0.2 0.2]
0.10915493647151904



In [13]:
n = 200

_1d_array_0 = np.random.normal(size=n)

_1d_array_1 = np.random.normal(size=n)

In [17]:
%%timeit

kraft.compute_information_coefficient_between_2_1d_arrays(
    _1d_array_0,
    _1d_array_1,
)

2.85 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
