In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import plotly

In [3]:
plotly.offline.init_notebook_mode(connected=True)

In [4]:
import numpy as np

In [5]:
observation_x_dimension = np.asarray((np.arange(0, 8),np.arange(0, 16, 2))).T

observation_x_dimension

array([[ 0,  0],
       [ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10],
       [ 6, 12],
       [ 7, 14]])

In [6]:
import kraft

In [7]:
n_grid = 16

In [8]:
mesh_grid_point_x_dimension, mesh_grid_point_joint_probability = kraft.compute_joint_probability(
    observation_x_dimension,
    n_grids=(n_grid, n_grid),
)

In [9]:
# mesh_grid_point_x_dimension

In [10]:
# mesh_grid_point_joint_probability

In [11]:
dimension_grids, joint_probability = kraft.unmesh(mesh_grid_point_x_dimension, mesh_grid_point_joint_probability)

In [12]:
dimension_grids

(array([-2.33333333e+00, -1.55555556e+00, -7.77777778e-01, -4.44089210e-16,
         7.77777778e-01,  1.55555556e+00,  2.33333333e+00,  3.11111111e+00,
         3.88888889e+00,  4.66666667e+00,  5.44444444e+00,  6.22222222e+00,
         7.00000000e+00,  7.77777778e+00,  8.55555556e+00,  9.33333333e+00]),
 array([-4.66666667e+00, -3.11111111e+00, -1.55555556e+00, -8.88178420e-16,
         1.55555556e+00,  3.11111111e+00,  4.66666667e+00,  6.22222222e+00,
         7.77777778e+00,  9.33333333e+00,  1.08888889e+01,  1.24444444e+01,
         1.40000000e+01,  1.55555556e+01,  1.71111111e+01,  1.86666667e+01]))

In [13]:
joint_probability

array([[9.42652753e-04, 1.85716399e-03, 2.98668844e-03, 3.97540639e-03,
        4.46372518e-03, 4.33243188e-03, 3.73544544e-03, 2.93346193e-03,
        2.13551883e-03, 1.45555336e-03, 9.34323872e-04, 5.65367788e-04,
        3.22148448e-04, 1.69584557e-04, 8.02608773e-05, 3.30907558e-05],
       [1.11619918e-03, 2.21494894e-03, 3.59738927e-03, 4.85402403e-03,
        5.55309137e-03, 5.52545694e-03, 4.91581684e-03, 4.00545743e-03,
        3.03676420e-03, 2.16017021e-03, 1.44849791e-03, 9.15541249e-04,
        5.42978255e-04, 2.95936674e-04, 1.44096350e-04, 6.07722719e-05],
       [1.24847262e-03, 2.49694279e-03, 4.09918906e-03, 5.61363932e-03,
        6.55299103e-03, 6.69589840e-03, 6.15693473e-03, 5.21184328e-03,
        4.11834639e-03, 3.05844846e-03, 2.14222428e-03, 1.41331051e-03,
        8.71412241e-04, 4.90964180e-04, 2.45540846e-04, 1.05768550e-04],
       [1.31929288e-03, 2.66126921e-03, 4.42035555e-03, 6.15149067e-03,
        7.33858918e-03, 7.71368445e-03, 7.34221390e-03, 6.464

In [14]:
mesh_grid_point_x_dimension, mesh_grid_point_posterior_probability = kraft.compute_posterior_probability(
    observation_x_dimension,
    n_grids=(n_grid, n_grid),
)

In [15]:
# mesh_grid_point_x_dimension

In [16]:
# mesh_grid_point_posterior_probability

In [17]:
dimension_grids, posterior_probability = kraft.unmesh(mesh_grid_point_x_dimension, mesh_grid_point_posterior_probability)

In [18]:
# dimension_grids

In [19]:
posterior_probability

array([[0.03048404, 0.06005803, 0.09658524, 0.12855897, 0.1443505 ,
        0.14010466, 0.12079897, 0.09486397, 0.06905963, 0.04707052,
        0.0302147 , 0.01828319, 0.01041782, 0.00548412, 0.00259552,
        0.00107011],
       [0.02763749, 0.05484292, 0.08907264, 0.12018736, 0.13749652,
        0.13681228, 0.12171738, 0.09917655, 0.07519136, 0.05348658,
        0.03586532, 0.02266913, 0.01344433, 0.0073275 , 0.00356788,
        0.00150474],
       [0.0247115 , 0.04942295, 0.08113683, 0.11111293, 0.12970588,
        0.1325345 , 0.12186659, 0.10316003, 0.08151602, 0.06053705,
        0.04240187, 0.0279742 , 0.0172482 , 0.00971784, 0.00486008,
        0.00209352],
       [0.02175348, 0.04388098, 0.0728861 , 0.10143034, 0.1210041 ,
        0.12718895, 0.12106386, 0.10658705, 0.08783805, 0.06811762,
        0.04982873, 0.03428554, 0.02195001, 0.01276375, 0.00654584,
        0.00287562],
       [0.01882164, 0.03832319, 0.06446965, 0.09129228, 0.11148163,
        0.12074655, 0.11914902, 