In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
array = np.arange(-2, 4)

array

array([-2, -1,  0,  1,  2,  3])

In [5]:
for standard_deviation in (-1, 0, 1, 2):
    
    print(standard_deviation)

    print(kraft.clip(array, standard_deviation))
    
    print()

-1
[-1.20782513 -1.20782513 -1.20782513 -1.20782513 -1.20782513 -1.20782513]

0
[0.5 0.5 0.5 0.5 0.5 0.5]

1
[-1.20782513 -1.          0.          1.          2.          2.20782513]

2
[-2. -1.  0.  1.  2.  3.]

