In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
array = np.arange(-2, 3)

array

array([-2, -1,  0,  1,  2])

In [4]:
for standard_deviation in range(3):

    print(standard_deviation)

    print(kraft.clip(array, standard_deviation))

    print()

0
[0. 0. 0. 0. 0.]

1
[-1.41421356 -1.          0.          1.          1.41421356]

2
[-2. -1.  0.  1.  2.]

