In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 0.0, np.nan),
    (0, 1),
    (0, 1, 0.0, 1.0),
    (np.nan, 0, 1, 0.0, 1.0),
    (0, 1, 2),
    (0, 1, 2, 0.0, 1.0, 2.0, np.nan),
    tuple(range(16)),
    (np.nan,) + tuple(range(16)),
    tuple(range(24)) + (np.nan,),
    (0.1,),
    np.random.random_sample(size=(2, 4)),
    np.random.randint(2, size=(2, 4)),
    np.random.randint(3, size=(2, 4)),
):
    
    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.guess_type(numbers))

    print()

[0]
binary

[0. 0.]
binary

[ 0.  0. nan]
binary

[0 1]
binary

[0. 1. 0. 1.]
binary

[nan  0.  1.  0.  1.]
binary

[0 1 2]
categorical

[ 0.  1.  2.  0.  1.  2. nan]
categorical

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
categorical

[nan  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
categorical

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. nan]
continuous

[0.1]
continuous

[[0.62781813 0.36846674 0.75851689 0.48971843]
 [0.28819915 0.35317804 0.69247078 0.26689165]]
continuous

[[1 0 1 0]
 [0 0 1 0]]
binary

[[0 0 2 2]
 [2 1 0 0]]
categorical

