In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

import kraft

In [3]:
for numbers in (
    (0,),
    (0, 0.0),
    (0, 1),
    (0, 1, 0.0, 1.0),
    np.random.randint(2, size=(2, 4)),
    (0, 1, 2),
    tuple(range(16)),
    np.random.randint(3, size=(2, 4)),
    (0.1,),
    tuple(range(17)),
    np.random.random_sample(size=(2, 4)),
):

    numbers = np.asarray(numbers)

    print(numbers)

    print(kraft.guess_type(numbers))

    print()

[0]
binary

[0. 0.]
binary

[0 1]
binary

[0. 1. 0. 1.]
binary

[[1 0 0 0]
 [1 1 0 0]]
binary

[0 1 2]
categorical

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
categorical

[[2 1 2 2]
 [0 1 0 2]]
categorical

[0.1]
continuous

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
continuous

[[0.26189331 0.37729832 0.65899479 0.92656085]
 [0.82067938 0.25064427 0.72921558 0.75936668]]
continuous

